BASE_URL = "http://127.0.0.1:8080"

VALID_PAYLOAD = {
    "gender_encoded": 1,
    "marital_status_encoded": 2,
    "housing_status_encoded": 2,
    "annual_income_normalized": 0.17,
    "savings_balance_normalized": 1.04,
    "checking_balance_normalized": 0.13,
    "loan_amount_normalized": 0.63,
    "loan_duration_months": 24,
    "existing_credits": 1,
    "past_due_count": 0,
    "credit_history_score": 0.5,
    "debt_ratio": 0.3,
    "loan_purpose_car": True,
    "loan_purpose_education": False,
    "loan_purpose_health": False,
    "loan_purpose_housing": False,
    "loan_purpose_other": False,
    "region_Assaba": False,
    "region_Brakna": False,
    "region_Gorgol": False,
    "region_Guidimakha": False,
    "region_Hodh_Ech_Chargui": False,
    "region_Hodh_El_Gharbi": False,
    "region_Inchiri": False,
    "region_Nouadhibou": False,
    "region_Nouakchott": True,
    "region_Tagant": False,
    "region_Trarza": False,
    "education_level_master": False,
    "education_level_phd": False,
    "education_level_primary": False,
    "education_level_secondary": True,
    "employment_status_public_sector": True,
    "employment_status_retired": False,
    "employment_status_self_employed": False,
    "employment_status_student": False,
    "employment_status_unemployed": False
}
